# Generated by Django 5.0.3 on 2024-04-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo da Monografia')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('palavrasChaves', models.TextField(verbose_name='Palavras-chaves')),
                ('dataEntrega', models.DateTimeField(verbose_name='Data de Entrega')),
                ('arquivo', models.FileField(blank=True, upload_to='documentos/pdfs/', verbose_name='Documento em PDF')),
                ('notaFinal', models.FloatField(blank=True, null=True, verbose_name='Nota final')),
                ('areaConcentracao', models.CharField(blank=True, choices=[('CSH', 'Ciências Sociais e Humanas'), ('CET', 'Ciências Exatas e Tecnológicas'), ('CSE', 'Ciências da Saúde'), ('CBA', 'Ciências Biológicas e Ambientais'), ('ACO', 'Artes e Comunicação'), ('EAO', 'Economia e Administração'), ('EDU', 'Educação'), ('DCJ', 'Direito e Ciências Jurídicas'), ('TIC', 'Tecnologia da Informação e Ciência da Computação')], max_length=50, null=True, verbose_name='Área de Concentração')),
                ('autor', models.ManyToManyField(related_name='autor_requests_created', to='equipe.pesquisador')),
                ('coorientador', models.ManyToManyField(related_name='coorientador_requests_created', to='equipe.pesquisador')),
                ('orientador', models.ManyToManyField(related_name='orientador_requests_created', to='equipe.pesquisador')),
            ],
        ),
    ]
